"""empty message

Revision ID: f1fb9122d38a
Revises:
Create Date: 2022-11-25 22:41:34.204470

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f1fb9122d38a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fulltextmodels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", postgresql.TSVECTOR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fulltextmodels")
    # ### end Alembic commands ###
